config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "movies#index"
  
  resources :movies do
    member do
      post '/comments' => 'movies#create_comment' # 자동으로 id에 setting 해준다.
    end
    
    collection do
      delete '/comments/:comment_id' => 'movies#destroy_comment'
      patch '/comments/:comment_id' => 'movies#update_comment'
    end
  end
  
  get '/likes/:movie_id' => 'movies#like_movie'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :movie
    belongs_to :user    
end

app/models/like.rb
class Like < ApplicationRecord
        belongs_to :user
        belongs_to :movie
end

app/models/movie.rb
class Movie < ApplicationRecord
    mount_uploader :image_path, ImageUploader
    has_many :likes
    has_many :users, through: :likes #likes를 통해서 많은 user를!
    has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :likes
  has_many :movies, through: :likes # likes를 통해서 movie
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
    def js_authenticate_user!
        render js: "location.href='/users/sign_in';" unless user_signed_in? # 로그인 되지않은 상태로 좋아요를 누르면 /users/sign_in으로 redirection.
    end  
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :js_authenticate_user!, only: [:like_movie]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_movie, only: [:show, :edit, :update, :destroy, :create_comment]

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
    @user_likes_movie = Like.where(user_id: current_user.id, movie_id: @movie.id).first if user_signed_in?
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)
    @movie.user_id = current_user.id # 저장하기 직전에 id 지정
    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def like_movie
      p params
      # 현재 유저와 params에 담긴 movie간의
      # 좋아요 관계를 설정한다. 끗
      
      @like = Like.where(user_id: current_user.id, movie_id: params[:movie_id]).first
      if @like.nil?
        @like = Like.create(user_id: current_user.id, movie_id: params[:movie_id])
      else
        @like.destroy
      end
     
      # 만약에 현재 로그인한 유저가 이미 좋아요를 눌렀을 경우
      # 해당 LIKE 인스턴스 삭제
      # 새로 누른 경우
      # 좋아요 관계 설정
      puts "좋아요 설정 THE END"
      
  end

  def create_comment
    #@movie = Movie.find(params[:id])
    @comment = Comment.create(user_id: current_user.id, movie_id: @movie.id, contents: params[:contents])
  end

  def destroy_comment
      @comment = Comment.find(params[:comment_id]).destroy
  end

  def update_comment
    @comment = Comment.find(params[:comment_id])
    @comment.update(contents: params[:contents])
  end
    
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title, :genre, :director, :actor, :description, :image_path)
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WatchaApp</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag    'application', media: 'all'%> <!--reload시 터보링크불러오는거 없앰-->
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <% flash.each do |k, v| %>
      <div class = "alert alert-<%= k %>"><%= v %></div>
    <%end%>
    <div class = "container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_for(movie) do |f| %> <!--movie자리에 다른거 넣으면 에러납니다.-->
  <% if movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class = "form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class = "form-group">
    <%= f.label :genre %>
    <%= f.text_field :genre, class: "form-control" %>
  </div>
  
  <div class = "form-group">
    <%= f.label :director %>
    <%= f.text_field :director, class: "form-control" %>
  </div>  

  <div class = "form-group">
    <%= f.label :actor %>
    <%= f.text_field :actor, class: "form-control" %>
  </div>

  <div class = "form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  
    <div class = "form-group">
    <%= f.label :image_path %>
    <%= f.file_field :image_path, class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movies/create_comment.js.erb
$('.comment-list').prepend(` 
        <li class = "comment-<%=@comment.id%> list-group-item d-flex justify-content-between">
            <span class="comment-detail-<%=@comment.id%>"><%=@comment.contents %></span>
        <div>
            <button data-id="<%=@comment.id %>" class="btn btn-warning edit-comment text-white">수정</button>
            <button data-id="<%=@comment.id %>" class="btn btn-danger destroy-comment">삭제</button>
        </div>
        </li>
        `);
//prepend는 추가되는것이 제일 위로 붙는다.(first of child)
//append는 추가되는 것이 가장 아래로 붙는다.(last of child)
$('.comment-contents').val('')
alert("댓글 등록이 완료 되었습니다");

app/views/movies/destroy_comment.js.erb
  alert("댓글 삭제가 완료되었습니다!");
  //$(this).parent().remove(); // parents로 주면 댓글 한번에 삭제되기에, parent로 찾아온다.
  $('.comment-<%= @comment.id%>').remove();

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<h1 id = "title">Movies</h1>

<div id = "title" class ="row">
<% @movies.each do |movie| %>
<div class="card col-md-3">
  <img class="card-img-top" src="<%= movie.image_path.thumb_fit.url %>" alt="">
  <div class="card-body">
    <h5 class="card-title"><%= movie.title%></h5>
    <p class="card-text"><%= movie.genre %></p>
    <p class="card-text"><%= movie.director %></p>
    <p class="card-text"><%= movie.actor %></p>
    <%= link_to "영화 정보보기", movie_path(movie) , class: 'btn btn-primary'%>
  </div>
</div>
<% end %>
</div>
<br>

<%= link_to 'New Movie', new_movie_path %>

<hr>
<% if user_signed_in? %>
<!-- 로그인 된 상태 -->
<%= current_user.email %>
<%= link_to "로그아웃", destroy_user_session_path, method: "delete" %>
<% else %>
<!-- 로그 아웃 된 상태 -->
<%= link_to "로그인", new_user_session_path %>
<%end%>
<script>
  // var btn = document.getElementsByClassName("btn")[0];
  // var count = 0;
  // var msg = "나 건드리지마!!";
  // btn.onmouseover= function(){ 
  //   count += 1; 
  //   if (count>3)
  //         { msg = "아 진짜 그만하라니까?";} 
  //     alert(msg);
  // }
    

  // var func1 = function(){ //선언 하고 나서 function을 사용할 수 있다.
  //   alert("하이욤!");
  //   //함수 표현식
  //   //선언되기 이전에 사용할 수 없다.
  // }

  // function func2() { // 선언하기전에 먼저 함수를 쓰고 그다음에 선언해도 사용가능하다.
  //   alert("하이하이욤!")
  //   //함수 선언식
  //   //선언되기 이전에도 사용할 수 있다.
    
  // }
  
  // var btn = document.getElementsByClassName("btn")[0];
  
  // btn.addEventListener("mouseover", func2);
  
  // var btn2 = document.getElementsByClassName("btn")[1];
  
  // btn2.onmouseover = func1;
  
  // 먼저 선언되어 있던 함수를 이벤트 핸들러로 사용할 경우
  // 함수 이름만 적어서 사용한다.
  // 함수이름() <- 이 형태는 함수의 실행을 의미한다.
  
  // 버튼 (요소)에 마우스를 오버(이벤트)했더니 (이벤트 리스너)
  // 그 위에 있던 글자(요소)들이 갑자기 이상한 글자로 변해버린다 (이벤트 핸들러)
/*  var count = 0;
  
  var title = document.getElementsByClassName("card-title")[0];
  console.dir(title);
  var default_text = title.innerText;
  
  var btn = document.getElementsByClassName("btn")[0]; //요소
  btn.addEventListener("mouseover", function(){
  if(count == 0){
    var title = document.getElementsByClassName("card-title")[0];
    console.dir(title);
    title.innerText = "Bie Mo Wo";
    count++;
  }
  // 함수를 선언하는 3번재 방법 : 익명함수  
  else{
    var title = document.getElementsByClassName("card-title")[0];
    console.dir(title);
    title.innerText = default_text;
    count--;
  }
  });*/
// innerHtml은 개발자 코드로 확인할 때, 코드 전체를 보여주고, innerText는 결과만 리턴


//마우스를 올렸을때, 버튼색상을 바꾸자(이벤트, 이벤트 리스너)
//해당 버튼의 class가 btn btn-danger 로 변경(이벤트 핸들러)

var title = document.getElementsByClassName("card-title")[0];
btn.addEventListener("mouseover", function(){
  btn.setAttribute("class", "btn btn-danger ");
})


</script>

app/views/movies/like_movie.js.erb
alert("좋아요~");
var like_count = parseInt($('.like-count').text());

if(<%=@like.frozen? %>){  //삭제되었을 경우에는 사용하지 못하도록 얼어져(frozen) 있다. - 좋아요 취소된 경우

// 좋아요가 취소된 경우
// 좋아요 취소버튼 -> 좋아요 버튼
    like_count = like_count - 1
    $('.like').html(`좋아요(<span class='like-count'>${like_count}</span>)`).toggleClass("btn-info btn-warning text-white");
} else {
// 좋아요가 새로 눌린 경우
// 좋아요 버튼 -> 좋아요 취소
    like_count = like_count + 1
    $('.like').html(`좋아요 취소(<span class='like-count'>${like_count}</span>)`).toggleClass("btn-warning btn-info text-white");
}

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<h1><%= @movie.title%></h1>
<hr>
<img class="card-img-top" src="<%= @movie.image_path.thumb_fit.url %>" alt="">
<hr>
<p><%= @movie.description %></p>
<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>
<hr>
<% if @user_like_movie.nil? %>
    <button class ="btn btn-info like">좋아요(<span class='like-count'><%=@movie.likes.count%>)</span></button>
<% else %>
     <button class="btn btn-warning text-white like">좋아요 취소(<span class='like-count'><%=@movie.likes.count%></span>)</button>
<% end %>
<hr>
<form class= "comment">
    <div class="row">
    <div class = "col">
        <input class="form-control comment-contents">
    </div>
    <div class = "col">
        <input type ="submit" value ="댓글 쓰기" class = "btn btn-success">
    </div>
    </div>
    <hr>
</form>
<hr>
<h3>댓글 목록</h3>
<br>
<ul class="list-group comment-list">
    <!--<li class="list-group-item">Cras justo odio</li>-->
    <!--기존에 등록 되어있는 댓글 출력하기-->
    <% @movie.comments.reverse.each do |comm|%> <!--movie 하나에 달려있는 댓글들을 가져온다-->       
        <li class = "comment-<%=comm.id%> list-group-item d-flex justify-content-between">
            <span class="comment-detail-<%= comm.id%>"><%= comm.contents %></span>
        <div>
            <button data-id="<%=comm.id %>" class="btn btn-warning edit-comment text-white">수정</button>
            <button data-id="<%=comm.id %>" class="btn btn-danger destroy-comment">삭제</button>
        </div>
        
        </li> <!--그 댓글들의 주소에서 contents를 가져온다-->
        
    <%end%>
</ul>
<hr>
<script>
    $(document).on('ready',function(){ //html문서(document)가 준비되었을때, 자바스크립트를 로드한다.
        $('.like').on('click', function(){
            console.log("likey!");
            $.ajax({
                url: '/likes/<%= @movie.id %>'
            });
        })
        $('.comment').on('submit', function(e){
            e.preventDefault(); //기본적으로 설정되어있는 이벤트를 막겠다.
            var comm = $('.comment-contents').val();
            console.log(comm);
            $.ajax({
                url:"/movies/<%= @movie.id %>/comments",
                method:"POST",
                data: {
                    contents:comm
                }
            })
        });
        
        $(document).on('click','.destroy-comment', function(){
            console.log("destroyed!")
          
            var comment_id = $(this).attr('data-id');
            //$(this).data('id');
            console.log(comment_id);
            $.ajax({
                url:"/movies/comments/" + comment_id,
                method: "delete"
            })
        });
        
        $(document).on('click','.edit-comment', function(){
            //$('.comment-detail').text();
            var comment_id = $(this).data('id');
            var edit_comment = $(`.comment-detail-${comment_id}`)
            var contents = edit_comment.text();
            edit_comment.html(`
            <input type="text" value="${contents}" class="form-control edit-comment-${comment_id}">`);
            $(this).text("확인").removeClass("edit-comment btn-warning text-white").addClass("update-comment btn-dark text-white");
        });
        
        $(document).on('click','.update-comment', function(){
            var comment_id = $(this).data('id');
            var comment_form = $(`.edit-comment-${comment_id}`)
            $.ajax({
                url: "/movies/comments/" + comment_id,
                method: "patch",
                data: {
                    contents:comment_form.val()
                }
            })
        });
    }); //자바 스크립트 코드를 짤때 항상 넣어주면 좋음.
</script>

app/views/movies/update_comment.js.erb
alert("수정 완료!");
var edit_comment = $('.comment-detail-<%= @comment.id %>')
edit_comment.html('<%=@comment.contents %>');
$('.update-comment').text("수정").removeClass("update-comment btn-dark text-white").addClass("edit-comment btn-warning text-white");